name: CI Cypress report

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  cypress-e2e-api:
    runs-on: ubuntu-latest
    name: Run Cypress E2E Tests
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
    steps:
      - name: Checkout code repository ðŸ“‚
        uses: actions/checkout@v3
      - name: Install Cypress ðŸ“¦
        run: npm install cypress
      - name: Cache Cypress dependencies ðŸ’»
        uses: actions/cache@v3
        id: cache-cypress-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cypress-deps-${{ matrix.cypress }}
      - name: Cache Cypress binary ðŸ’»
        uses: actions/cache@v3
        id: cache-cypress-binary
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-binary-${{ matrix.cypress }}
      - name: Restore Cypress dependencies ðŸ”™
        uses: actions/cache@v3
        id: restore-cypress-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cypress-deps-${{ matrix.cypress }}
      - name: Restore Cypress binary ðŸ”™
        uses: actions/cache@v3
        id: restore-cypress-binary
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-binary-${{ matrix.cypress }}
      - name: Run Cypress tests ðŸ§ª
        uses: cypress-io/github-action@v5
        continue-on-error: true
        with:
          browser: chrome
        env:
          CYPRESS_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Run CodeClimate ðŸ§ª
        uses: paambaati/codeclimate-action@latest
        with:
          token: ${{ secrets.CODECLIMATE_TOKEN }}
          repo: ${{ github.repository }}
          format: html
          output: codeclimate-report.html
      - name: Merge test results into one ðŸ“Š
        run: npm run report:merge
      - name: Generate HTML report ðŸ“Š
        run: npm run report:generate
      - name: Publish report to GitHub Pages ðŸ“„
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public